backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "public/images/articles"
public_folder: "/images/articles"

collections:
  - name: "articles"
    label: "Articles"
    folder: "src/content/articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Description", name: "description", widget: "string", required: true }
      - { label: "Publish Date", name: "pubDate", widget: "datetime", date_format: "YYYY-MM-DD", time_format: false, required: true }
      - { label: "Author", name: "author", widget: "string", default: "FHIRBall Alliance", required: false }
      - { label: "Featured Image", name: "image", widget: "image", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
